# Generated by Django 5.1.1 on 2024-10-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fremdwort', models.CharField(max_length=100)),
                ('übersetzung', models.CharField(max_length=100)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie')),
            ],
        ),
    ]
