# Generated by Django 5.1.1 on 2024-10-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wort',
            old_name='fremdwort',
            new_name='deutsch',
        ),
        migrations.RenameField(
            model_name='wort',
            old_name='übersetzung',
            new_name='englisch',
        ),
    ]
