# Generated by Django 5.1.1 on 2024-10-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_fremdwort_wort_deutsch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wort',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie', verbose_name='Wörter'),
        ),
    ]
