# Generated by Django 5.1.1 on 2024-10-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_rename_englisch_wort_finnisch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wort',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie'),
        ),
        migrations.CreateModel(
            name='Satz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deutsch', models.CharField(max_length=255)),
                ('finnisch', models.CharField(max_length=255)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie')),
            ],
        ),
    ]
