# Generated by Django 5.1.1 on 2024-10-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_alter_wort_kategorie_satz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wort',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie'),
        ),
    ]
