# Generated by Django 5.1.1 on 2024-10-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_wort_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='satz',
            name='merksatz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wort',
            name='merksatz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satz',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie'),
        ),
    ]
