# Generated by Django 5.1.1 on 2024-10-08 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_satz_merksatz_wort_merksatz_alter_satz_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satz',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satz',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie'),
        ),
        migrations.AlterField(
            model_name='wort',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wort',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie'),
        ),
    ]
