# Generated by Django 5.1.1 on 2024-10-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_alter_kategorie_id_alter_satz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satz',
            name='kategorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie'),
        ),
    ]
