# Generated by Django 5.1.1 on 2024-10-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_alter_satz_kategorie_alter_wort_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satz',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie'),
        ),
        migrations.AlterField(
            model_name='wort',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.kategorie'),
        ),
    ]
